### PR TITLE
Import and export graph names.

### LINKED ISSUE #42: Import and export DOT with a graph name
It’s just `tesseract` for every graph at the moment.

### PR DESCRIPTION
**Pull request by amackworth**
Fixes #42.

### CODE REVIEW

**Comment by robrix** [comment]
Kudos on the initiative, but I don’t think this is the direction this should take. Graphs should remain abstract; rather, we’d import/export `(String, Graph<T>)` pairs.

**Comment by amackworth** [comment]
How's that look?

**Comment by robrix** [comment]
That’s the stuff! Nice one, thank you.

**Comment by amackworth** [comment]
🙏

**Pull request merged**
